version: '3.8'

services:
  # La base de données PostgreSQL
  db:
    image: postgres:15
    container_name: wedding_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wedding_db
    ports:
      - "5432:5432"

  # Ton backend FastAPI
  backend:
    build: ./backend
    container_name: wedding_api
    volumes:
      - ./backend:/app
      - /app/.venv  # Astuce : Crée un volume anonyme pour éviter que le .venv Windows n'écrase celui du conteneur
    environment:
      - PYTHONPATH=/app
    # On force la commande de démarrage ici pour être sûr du chemin
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - db

  # Interface graphique Web pour la BDD
  adminer:
    image: adminer
    container_name: wedding_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db